# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold magenta)'
error_symbol = "[$ ](red bold)"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Format for prompt
format = """
$username\
$directory\
$git_branch\
$git_status\
$character
"""

[username]
style_user = "green"
format = "[$user]($style)"
show_always = true

[directory]
style = "cyan bold"
format = "[$path]($style)"
truncation_length = 3

[git_branch]
style = "white"
format = "[$branch]($style)"

[git_status]
style = "white"
format = '([\[$all_status$ahead_behind\]]($style))'
