export EDITOR=code
export BASH_SILENCE_DEPRECATION_WARNING=1
export TERM=xterm-256color

# Use Homebrew's bash if available
if [ -f /usr/local/bin/bash ]; then
    export SHELL=/usr/local/bin/bash
elif [ -f /opt/homebrew/bin/bash ]; then
    export SHELL=/opt/homebrew/bin/bash
fi

# Bash Aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Load specific OS bash config
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ -f ~/.bash_macos ]; then
        . ~/.bash_macos
    fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [ -f ~/.bashrc_linux ]; then
        . ~/.bashrc_linux
    fi
fi

# Load Starship
CONFIG_DIR=~/Sources/configurations

eval "$(starship init bash)"
#direnv hooks
eval "$(direnv hook bash)"
eval "$(fzf --bash)"
export STARSHIP_CONFIG=$CONFIG_DIR/starship/starship.toml
export KITTY_CONFIG_DIRECTORY=$CONFIG_DIR/kitty_conf/

. "$HOME/.local/bin/env"
